### ISSUE TITLE
.json support for saved data

### ISSUE THREAD

**Issue by Aleadinglight** [Aleadinglight/Smart-House-Alarm#5]
### Description
I think we will save timers as a list of `json` object. For example:

```yaml
[
    {
        "name": "Good Morning Vietnam",
        "id": 1,
        "sound_id": 1,
        "time": "08:00:00"
    },
    {
        "name": "Money talks"
        "id": 2,
        "sound_id": 2,
        "time": "03:50:00"
    }
]
```
